System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "wwwroot/js/feature1.min.js": [
      "app/feature1/main.js",
      "app/feature1/feature1.css!github:systemjs/plugin-css@0.1.33.js",
      "app/feature1/tmp/templates.js",
      "app/services/sample.service.js",
      "app/environment.js",
      "github:angular/bower-angular@1.6.3.js",
      "github:angular/bower-angular@1.6.3/angular.js",
      "app/feature1/components/app/app.component.js",
      "npm:rxjs@5.2.0.js",
      "npm:rxjs@5.2.0/Rx.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.9.js",
      "npm:process@0.11.9/browser.js",
      "npm:rxjs@5.2.0/symbol/observable.js",
      "npm:rxjs@5.2.0/util/root.js",
      "npm:rxjs@5.2.0/symbol/iterator.js",
      "npm:rxjs@5.2.0/symbol/rxSubscriber.js",
      "npm:rxjs@5.2.0/scheduler/animationFrame.js",
      "npm:rxjs@5.2.0/scheduler/AnimationFrameScheduler.js",
      "npm:rxjs@5.2.0/scheduler/AsyncScheduler.js",
      "npm:rxjs@5.2.0/Scheduler.js",
      "npm:rxjs@5.2.0/scheduler/AnimationFrameAction.js",
      "npm:rxjs@5.2.0/util/AnimationFrame.js",
      "npm:rxjs@5.2.0/scheduler/AsyncAction.js",
      "npm:rxjs@5.2.0/scheduler/Action.js",
      "npm:rxjs@5.2.0/Subscription.js",
      "npm:rxjs@5.2.0/util/UnsubscriptionError.js",
      "npm:rxjs@5.2.0/util/errorObject.js",
      "npm:rxjs@5.2.0/util/tryCatch.js",
      "npm:rxjs@5.2.0/util/isFunction.js",
      "npm:rxjs@5.2.0/util/isObject.js",
      "npm:rxjs@5.2.0/util/isArray.js",
      "npm:rxjs@5.2.0/scheduler/queue.js",
      "npm:rxjs@5.2.0/scheduler/QueueScheduler.js",
      "npm:rxjs@5.2.0/scheduler/QueueAction.js",
      "npm:rxjs@5.2.0/scheduler/async.js",
      "npm:rxjs@5.2.0/scheduler/asap.js",
      "npm:rxjs@5.2.0/scheduler/AsapScheduler.js",
      "npm:rxjs@5.2.0/scheduler/AsapAction.js",
      "npm:rxjs@5.2.0/util/Immediate.js",
      "npm:rxjs@5.2.0/observable/dom/AjaxObservable.js",
      "npm:rxjs@5.2.0/operator/map.js",
      "npm:rxjs@5.2.0/Subscriber.js",
      "npm:rxjs@5.2.0/Observer.js",
      "npm:rxjs@5.2.0/Observable.js",
      "npm:rxjs@5.2.0/util/toSubscriber.js",
      "npm:rxjs@5.2.0/scheduler/VirtualTimeScheduler.js",
      "npm:rxjs@5.2.0/testing/TestScheduler.js",
      "npm:rxjs@5.2.0/testing/SubscriptionLog.js",
      "npm:rxjs@5.2.0/testing/HotObservable.js",
      "npm:rxjs@5.2.0/util/applyMixins.js",
      "npm:rxjs@5.2.0/testing/SubscriptionLoggable.js",
      "npm:rxjs@5.2.0/Subject.js",
      "npm:rxjs@5.2.0/SubjectSubscription.js",
      "npm:rxjs@5.2.0/util/ObjectUnsubscribedError.js",
      "npm:rxjs@5.2.0/testing/ColdObservable.js",
      "npm:rxjs@5.2.0/Notification.js",
      "npm:rxjs@5.2.0/operator/timestamp.js",
      "npm:rxjs@5.2.0/operator/timeInterval.js",
      "npm:rxjs@5.2.0/util/TimeoutError.js",
      "npm:rxjs@5.2.0/util/ArgumentOutOfRangeError.js",
      "npm:rxjs@5.2.0/util/EmptyError.js",
      "npm:rxjs@5.2.0/observable/ConnectableObservable.js",
      "npm:rxjs@5.2.0/BehaviorSubject.js",
      "npm:rxjs@5.2.0/ReplaySubject.js",
      "npm:rxjs@5.2.0/operator/observeOn.js",
      "npm:rxjs@5.2.0/AsyncSubject.js",
      "npm:rxjs@5.2.0/add/operator/zipAll.js",
      "npm:rxjs@5.2.0/operator/zipAll.js",
      "npm:rxjs@5.2.0/operator/zip.js",
      "npm:rxjs@5.2.0/util/subscribeToResult.js",
      "npm:rxjs@5.2.0/InnerSubscriber.js",
      "npm:rxjs@5.2.0/util/isPromise.js",
      "npm:rxjs@5.2.0/util/isArrayLike.js",
      "npm:rxjs@5.2.0/OuterSubscriber.js",
      "npm:rxjs@5.2.0/observable/ArrayObservable.js",
      "npm:rxjs@5.2.0/util/isScheduler.js",
      "npm:rxjs@5.2.0/observable/EmptyObservable.js",
      "npm:rxjs@5.2.0/observable/ScalarObservable.js",
      "npm:rxjs@5.2.0/add/operator/zip.js",
      "npm:rxjs@5.2.0/add/operator/withLatestFrom.js",
      "npm:rxjs@5.2.0/operator/withLatestFrom.js",
      "npm:rxjs@5.2.0/add/operator/windowWhen.js",
      "npm:rxjs@5.2.0/operator/windowWhen.js",
      "npm:rxjs@5.2.0/add/operator/windowToggle.js",
      "npm:rxjs@5.2.0/operator/windowToggle.js",
      "npm:rxjs@5.2.0/add/operator/windowTime.js",
      "npm:rxjs@5.2.0/operator/windowTime.js",
      "npm:rxjs@5.2.0/util/isNumeric.js",
      "npm:rxjs@5.2.0/add/operator/windowCount.js",
      "npm:rxjs@5.2.0/operator/windowCount.js",
      "npm:rxjs@5.2.0/add/operator/window.js",
      "npm:rxjs@5.2.0/operator/window.js",
      "npm:rxjs@5.2.0/add/operator/toPromise.js",
      "npm:rxjs@5.2.0/operator/toPromise.js",
      "npm:rxjs@5.2.0/add/operator/toArray.js",
      "npm:rxjs@5.2.0/operator/toArray.js",
      "npm:rxjs@5.2.0/add/operator/timestamp.js",
      "npm:rxjs@5.2.0/add/operator/timeoutWith.js",
      "npm:rxjs@5.2.0/operator/timeoutWith.js",
      "npm:rxjs@5.2.0/util/isDate.js",
      "npm:rxjs@5.2.0/add/operator/timeout.js",
      "npm:rxjs@5.2.0/operator/timeout.js",
      "npm:rxjs@5.2.0/add/operator/timeInterval.js",
      "npm:rxjs@5.2.0/add/operator/throttleTime.js",
      "npm:rxjs@5.2.0/operator/throttleTime.js",
      "npm:rxjs@5.2.0/add/operator/throttle.js",
      "npm:rxjs@5.2.0/operator/throttle.js",
      "npm:rxjs@5.2.0/add/operator/takeWhile.js",
      "npm:rxjs@5.2.0/operator/takeWhile.js",
      "npm:rxjs@5.2.0/add/operator/takeUntil.js",
      "npm:rxjs@5.2.0/operator/takeUntil.js",
      "npm:rxjs@5.2.0/add/operator/takeLast.js",
      "npm:rxjs@5.2.0/operator/takeLast.js",
      "npm:rxjs@5.2.0/add/operator/take.js",
      "npm:rxjs@5.2.0/operator/take.js",
      "npm:rxjs@5.2.0/add/operator/switchMapTo.js",
      "npm:rxjs@5.2.0/operator/switchMapTo.js",
      "npm:rxjs@5.2.0/add/operator/switchMap.js",
      "npm:rxjs@5.2.0/operator/switchMap.js",
      "npm:rxjs@5.2.0/add/operator/switch.js",
      "npm:rxjs@5.2.0/operator/switch.js",
      "npm:rxjs@5.2.0/add/operator/subscribeOn.js",
      "npm:rxjs@5.2.0/operator/subscribeOn.js",
      "npm:rxjs@5.2.0/observable/SubscribeOnObservable.js",
      "npm:rxjs@5.2.0/add/operator/startWith.js",
      "npm:rxjs@5.2.0/operator/startWith.js",
      "npm:rxjs@5.2.0/operator/concat.js",
      "npm:rxjs@5.2.0/operator/mergeAll.js",
      "npm:rxjs@5.2.0/add/operator/skipWhile.js",
      "npm:rxjs@5.2.0/operator/skipWhile.js",
      "npm:rxjs@5.2.0/add/operator/skipUntil.js",
      "npm:rxjs@5.2.0/operator/skipUntil.js",
      "npm:rxjs@5.2.0/add/operator/skip.js",
      "npm:rxjs@5.2.0/operator/skip.js",
      "npm:rxjs@5.2.0/add/operator/single.js",
      "npm:rxjs@5.2.0/operator/single.js",
      "npm:rxjs@5.2.0/add/operator/share.js",
      "npm:rxjs@5.2.0/operator/share.js",
      "npm:rxjs@5.2.0/operator/multicast.js",
      "npm:rxjs@5.2.0/add/operator/sequenceEqual.js",
      "npm:rxjs@5.2.0/operator/sequenceEqual.js",
      "npm:rxjs@5.2.0/add/operator/scan.js",
      "npm:rxjs@5.2.0/operator/scan.js",
      "npm:rxjs@5.2.0/add/operator/sampleTime.js",
      "npm:rxjs@5.2.0/operator/sampleTime.js",
      "npm:rxjs@5.2.0/add/operator/sample.js",
      "npm:rxjs@5.2.0/operator/sample.js",
      "npm:rxjs@5.2.0/add/operator/retryWhen.js",
      "npm:rxjs@5.2.0/operator/retryWhen.js",
      "npm:rxjs@5.2.0/add/operator/retry.js",
      "npm:rxjs@5.2.0/operator/retry.js",
      "npm:rxjs@5.2.0/add/operator/repeatWhen.js",
      "npm:rxjs@5.2.0/operator/repeatWhen.js",
      "npm:rxjs@5.2.0/add/operator/repeat.js",
      "npm:rxjs@5.2.0/operator/repeat.js",
      "npm:rxjs@5.2.0/add/operator/reduce.js",
      "npm:rxjs@5.2.0/operator/reduce.js",
      "npm:rxjs@5.2.0/add/operator/race.js",
      "npm:rxjs@5.2.0/operator/race.js",
      "npm:rxjs@5.2.0/add/operator/publishLast.js",
      "npm:rxjs@5.2.0/operator/publishLast.js",
      "npm:rxjs@5.2.0/add/operator/publishReplay.js",
      "npm:rxjs@5.2.0/operator/publishReplay.js",
      "npm:rxjs@5.2.0/add/operator/publishBehavior.js",
      "npm:rxjs@5.2.0/operator/publishBehavior.js",
      "npm:rxjs@5.2.0/add/operator/publish.js",
      "npm:rxjs@5.2.0/operator/publish.js",
      "npm:rxjs@5.2.0/add/operator/pluck.js",
      "npm:rxjs@5.2.0/operator/pluck.js",
      "npm:rxjs@5.2.0/add/operator/partition.js",
      "npm:rxjs@5.2.0/operator/partition.js",
      "npm:rxjs@5.2.0/operator/filter.js",
      "npm:rxjs@5.2.0/util/not.js",
      "npm:rxjs@5.2.0/add/operator/pairwise.js",
      "npm:rxjs@5.2.0/operator/pairwise.js",
      "npm:rxjs@5.2.0/add/operator/onErrorResumeNext.js",
      "npm:rxjs@5.2.0/operator/onErrorResumeNext.js",
      "npm:rxjs@5.2.0/observable/FromObservable.js",
      "npm:rxjs@5.2.0/observable/ArrayLikeObservable.js",
      "npm:rxjs@5.2.0/observable/IteratorObservable.js",
      "npm:rxjs@5.2.0/observable/PromiseObservable.js",
      "npm:rxjs@5.2.0/add/operator/observeOn.js",
      "npm:rxjs@5.2.0/add/operator/multicast.js",
      "npm:rxjs@5.2.0/add/operator/min.js",
      "npm:rxjs@5.2.0/operator/min.js",
      "npm:rxjs@5.2.0/add/operator/mergeScan.js",
      "npm:rxjs@5.2.0/operator/mergeScan.js",
      "npm:rxjs@5.2.0/add/operator/mergeMapTo.js",
      "npm:rxjs@5.2.0/operator/mergeMapTo.js",
      "npm:rxjs@5.2.0/add/operator/mergeMap.js",
      "npm:rxjs@5.2.0/operator/mergeMap.js",
      "npm:rxjs@5.2.0/add/operator/mergeAll.js",
      "npm:rxjs@5.2.0/add/operator/merge.js",
      "npm:rxjs@5.2.0/operator/merge.js",
      "npm:rxjs@5.2.0/add/operator/max.js",
      "npm:rxjs@5.2.0/operator/max.js",
      "npm:rxjs@5.2.0/add/operator/materialize.js",
      "npm:rxjs@5.2.0/operator/materialize.js",
      "npm:rxjs@5.2.0/add/operator/mapTo.js",
      "npm:rxjs@5.2.0/operator/mapTo.js",
      "npm:rxjs@5.2.0/add/operator/map.js",
      "npm:rxjs@5.2.0/add/operator/every.js",
      "npm:rxjs@5.2.0/operator/every.js",
      "npm:rxjs@5.2.0/add/operator/let.js",
      "npm:rxjs@5.2.0/operator/let.js",
      "npm:rxjs@5.2.0/add/operator/last.js",
      "npm:rxjs@5.2.0/operator/last.js",
      "npm:rxjs@5.2.0/add/operator/auditTime.js",
      "npm:rxjs@5.2.0/operator/auditTime.js",
      "npm:rxjs@5.2.0/add/operator/audit.js",
      "npm:rxjs@5.2.0/operator/audit.js",
      "npm:rxjs@5.2.0/add/operator/isEmpty.js",
      "npm:rxjs@5.2.0/operator/isEmpty.js",
      "npm:rxjs@5.2.0/add/operator/ignoreElements.js",
      "npm:rxjs@5.2.0/operator/ignoreElements.js",
      "npm:rxjs@5.2.0/util/noop.js",
      "npm:rxjs@5.2.0/add/operator/groupBy.js",
      "npm:rxjs@5.2.0/operator/groupBy.js",
      "npm:rxjs@5.2.0/util/FastMap.js",
      "npm:rxjs@5.2.0/util/Map.js",
      "npm:rxjs@5.2.0/util/MapPolyfill.js",
      "npm:rxjs@5.2.0/add/operator/first.js",
      "npm:rxjs@5.2.0/operator/first.js",
      "npm:rxjs@5.2.0/add/operator/findIndex.js",
      "npm:rxjs@5.2.0/operator/findIndex.js",
      "npm:rxjs@5.2.0/operator/find.js",
      "npm:rxjs@5.2.0/add/operator/find.js",
      "npm:rxjs@5.2.0/add/operator/finally.js",
      "npm:rxjs@5.2.0/operator/finally.js",
      "npm:rxjs@5.2.0/add/operator/filter.js",
      "npm:rxjs@5.2.0/add/operator/elementAt.js",
      "npm:rxjs@5.2.0/operator/elementAt.js",
      "npm:rxjs@5.2.0/add/operator/expand.js",
      "npm:rxjs@5.2.0/operator/expand.js",
      "npm:rxjs@5.2.0/add/operator/exhaustMap.js",
      "npm:rxjs@5.2.0/operator/exhaustMap.js",
      "npm:rxjs@5.2.0/add/operator/exhaust.js",
      "npm:rxjs@5.2.0/operator/exhaust.js",
      "npm:rxjs@5.2.0/add/operator/do.js",
      "npm:rxjs@5.2.0/operator/do.js",
      "npm:rxjs@5.2.0/add/operator/distinctUntilKeyChanged.js",
      "npm:rxjs@5.2.0/operator/distinctUntilKeyChanged.js",
      "npm:rxjs@5.2.0/operator/distinctUntilChanged.js",
      "npm:rxjs@5.2.0/add/operator/distinctUntilChanged.js",
      "npm:rxjs@5.2.0/add/operator/distinct.js",
      "npm:rxjs@5.2.0/operator/distinct.js",
      "npm:rxjs@5.2.0/util/Set.js",
      "npm:rxjs@5.2.0/add/operator/delayWhen.js",
      "npm:rxjs@5.2.0/operator/delayWhen.js",
      "npm:rxjs@5.2.0/add/operator/delay.js",
      "npm:rxjs@5.2.0/operator/delay.js",
      "npm:rxjs@5.2.0/add/operator/defaultIfEmpty.js",
      "npm:rxjs@5.2.0/operator/defaultIfEmpty.js",
      "npm:rxjs@5.2.0/add/operator/debounceTime.js",
      "npm:rxjs@5.2.0/operator/debounceTime.js",
      "npm:rxjs@5.2.0/add/operator/debounce.js",
      "npm:rxjs@5.2.0/operator/debounce.js",
      "npm:rxjs@5.2.0/add/operator/dematerialize.js",
      "npm:rxjs@5.2.0/operator/dematerialize.js",
      "npm:rxjs@5.2.0/add/operator/count.js",
      "npm:rxjs@5.2.0/operator/count.js",
      "npm:rxjs@5.2.0/add/operator/concatMapTo.js",
      "npm:rxjs@5.2.0/operator/concatMapTo.js",
      "npm:rxjs@5.2.0/add/operator/concatMap.js",
      "npm:rxjs@5.2.0/operator/concatMap.js",
      "npm:rxjs@5.2.0/add/operator/concatAll.js",
      "npm:rxjs@5.2.0/operator/concatAll.js",
      "npm:rxjs@5.2.0/add/operator/concat.js",
      "npm:rxjs@5.2.0/add/operator/combineLatest.js",
      "npm:rxjs@5.2.0/operator/combineLatest.js",
      "npm:rxjs@5.2.0/add/operator/combineAll.js",
      "npm:rxjs@5.2.0/operator/combineAll.js",
      "npm:rxjs@5.2.0/add/operator/catch.js",
      "npm:rxjs@5.2.0/operator/catch.js",
      "npm:rxjs@5.2.0/add/operator/bufferWhen.js",
      "npm:rxjs@5.2.0/operator/bufferWhen.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:ieee754@1.1.8.js",
      "npm:ieee754@1.1.8/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:rxjs@5.2.0/add/operator/bufferToggle.js",
      "npm:rxjs@5.2.0/operator/bufferToggle.js",
      "npm:rxjs@5.2.0/add/operator/bufferTime.js",
      "npm:rxjs@5.2.0/operator/bufferTime.js",
      "npm:rxjs@5.2.0/add/operator/bufferCount.js",
      "npm:rxjs@5.2.0/operator/bufferCount.js",
      "npm:rxjs@5.2.0/add/operator/buffer.js",
      "npm:rxjs@5.2.0/operator/buffer.js",
      "npm:rxjs@5.2.0/add/observable/dom/webSocket.js",
      "npm:rxjs@5.2.0/observable/dom/webSocket.js",
      "npm:rxjs@5.2.0/observable/dom/WebSocketSubject.js",
      "npm:rxjs@5.2.0/util/assign.js",
      "npm:rxjs@5.2.0/add/observable/dom/ajax.js",
      "npm:rxjs@5.2.0/observable/dom/ajax.js",
      "npm:rxjs@5.2.0/add/observable/zip.js",
      "npm:rxjs@5.2.0/observable/zip.js",
      "npm:rxjs@5.2.0/add/observable/timer.js",
      "npm:rxjs@5.2.0/observable/timer.js",
      "npm:rxjs@5.2.0/observable/TimerObservable.js",
      "npm:rxjs@5.2.0/add/observable/throw.js",
      "npm:rxjs@5.2.0/observable/throw.js",
      "npm:rxjs@5.2.0/observable/ErrorObservable.js",
      "npm:rxjs@5.2.0/add/observable/using.js",
      "npm:rxjs@5.2.0/observable/using.js",
      "npm:rxjs@5.2.0/observable/UsingObservable.js",
      "npm:rxjs@5.2.0/add/observable/range.js",
      "npm:rxjs@5.2.0/observable/range.js",
      "npm:rxjs@5.2.0/observable/RangeObservable.js",
      "npm:rxjs@5.2.0/add/observable/pairs.js",
      "npm:rxjs@5.2.0/observable/pairs.js",
      "npm:rxjs@5.2.0/observable/PairsObservable.js",
      "npm:rxjs@5.2.0/add/observable/onErrorResumeNext.js",
      "npm:rxjs@5.2.0/add/observable/of.js",
      "npm:rxjs@5.2.0/observable/of.js",
      "npm:rxjs@5.2.0/add/observable/never.js",
      "npm:rxjs@5.2.0/observable/never.js",
      "npm:rxjs@5.2.0/observable/NeverObservable.js",
      "npm:rxjs@5.2.0/add/observable/race.js",
      "npm:rxjs@5.2.0/add/observable/merge.js",
      "npm:rxjs@5.2.0/observable/merge.js",
      "npm:rxjs@5.2.0/add/observable/interval.js",
      "npm:rxjs@5.2.0/observable/interval.js",
      "npm:rxjs@5.2.0/observable/IntervalObservable.js",
      "npm:rxjs@5.2.0/add/observable/if.js",
      "npm:rxjs@5.2.0/observable/if.js",
      "npm:rxjs@5.2.0/observable/IfObservable.js",
      "npm:rxjs@5.2.0/add/observable/generate.js",
      "npm:rxjs@5.2.0/observable/GenerateObservable.js",
      "npm:rxjs@5.2.0/add/observable/fromPromise.js",
      "npm:rxjs@5.2.0/observable/fromPromise.js",
      "npm:rxjs@5.2.0/add/observable/fromEventPattern.js",
      "npm:rxjs@5.2.0/observable/fromEventPattern.js",
      "npm:rxjs@5.2.0/observable/FromEventPatternObservable.js",
      "npm:rxjs@5.2.0/add/observable/fromEvent.js",
      "npm:rxjs@5.2.0/observable/fromEvent.js",
      "npm:rxjs@5.2.0/observable/FromEventObservable.js",
      "npm:rxjs@5.2.0/add/observable/from.js",
      "npm:rxjs@5.2.0/observable/from.js",
      "npm:rxjs@5.2.0/add/observable/forkJoin.js",
      "npm:rxjs@5.2.0/observable/forkJoin.js",
      "npm:rxjs@5.2.0/observable/ForkJoinObservable.js",
      "npm:rxjs@5.2.0/add/observable/empty.js",
      "npm:rxjs@5.2.0/observable/empty.js",
      "npm:rxjs@5.2.0/add/observable/defer.js",
      "npm:rxjs@5.2.0/observable/defer.js",
      "npm:rxjs@5.2.0/observable/DeferObservable.js",
      "npm:rxjs@5.2.0/add/observable/concat.js",
      "npm:rxjs@5.2.0/observable/concat.js",
      "npm:rxjs@5.2.0/add/observable/combineLatest.js",
      "npm:rxjs@5.2.0/observable/combineLatest.js",
      "npm:rxjs@5.2.0/add/observable/bindNodeCallback.js",
      "npm:rxjs@5.2.0/observable/bindNodeCallback.js",
      "npm:rxjs@5.2.0/observable/BoundNodeCallbackObservable.js",
      "npm:rxjs@5.2.0/add/observable/bindCallback.js",
      "npm:rxjs@5.2.0/observable/bindCallback.js",
      "npm:rxjs@5.2.0/observable/BoundCallbackObservable.js",
      "github:angular/bower-angular-sanitize@1.6.3.js",
      "github:angular/bower-angular-sanitize@1.6.3/angular-sanitize.js",
      "github:angular/bower-angular-animate@1.6.3.js",
      "github:angular/bower-angular-animate@1.6.3/angular-animate.js",
      "npm:jquery@3.2.1.js",
      "npm:jquery@3.2.1/dist/jquery.js"
    ]
  },

  packages: {
    "app/feature1": {
      "main": "main.js",
      "defaultJSxtension": "js"
    }
  },

  map: {
    "angular": "github:angular/bower-angular@1.6.3",
    "angular-animate": "github:angular/bower-angular-animate@1.6.3",
    "angular-sanitize": "github:angular/bower-angular-sanitize@1.6.3",
    "css": "github:systemjs/plugin-css@0.1.33",
    "jquery": "npm:jquery@3.2.1",
    "rxjs": "npm:rxjs@5.2.0",
    "github:angular/bower-angular-animate@1.6.3": {
      "angular": "github:angular/bower-angular@1.6.3"
    },
    "github:angular/bower-angular-sanitize@1.6.3": {
      "angular": "github:angular/bower-angular@1.6.3"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.9"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.8",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:process@0.11.9": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:rxjs@5.2.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "symbol-observable": "npm:symbol-observable@1.0.4"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  }
});
